title: Alexander Walsh
description: Home

theme: just-the-docs

url: "https://alexanderwalsh.dev"
baseurl: ""

search_enabled: true
heading_anchors: true
color_scheme: dark

footer_content: "Copyright &copy; 2026 Alex Walsh"