title: Alexander Walsh
description: Home page
theme: just-the-docs

url: https://walshyaw.github.io

aux_links:
  "Template Repository":
    - "https://github.com/just-the-docs/just-the-docs-template"
