title: Walsh

theme: just-the-docs

url: "https://alexanderwalsh.dev"
baseurl: ""

search_enabled: false
heading_anchors: true
color_scheme: custom
favicon_ico: "/portfolio/images/favicon.ico"
logo: "/portfolio/images/favicon.ico"

footer_content: >
  contact@alexanderwalsh.dev
  <br/>
  Copyright &copy; 2026 Alexander Walsh
